import cadquery as cq

def ring(diameter, thickness):
    'create a horizontal ring with diameter and thickness'
    pass

def base(diameter, height):
    pass

def neck(bottom_d, top_d, height):
    pass

def top(diameter, piece):
    
    def pawn():
        pass
    
    def rook():
        pass

    def knight():
        pass

    def bishop():
        pass

    def queen():
        pass

    def king():
        pass
    
    return

def add_rings(rings):
    pass

def build_piece(specs):
    pass

def build_set():
    pass


if __name__ == '__main__':
    print 'This is the chessbits script.'